apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  namespace: cicd
spec:
  selector:
    app: django-notes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
